<?xml version="1.0"?>
  <!-- =================================================================================== -->
  <!-- |    LINKS                                                                        | -->
  <!-- =================================================================================== -->
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro" name="${namespace}">

    <!-- =================================================================================== -->
    <!-- |    VARIABLES  LINKS GLOBALES                                                    | -->
    <!-- =================================================================================== -->
    <xacro:property name="base_footprint" value="base_footprint"/>
    <xacro:property name="base_link" value="base_link"/>
    <xacro:property name="wheel_left_link" value="wheel_left_link"/>
    <xacro:property name="wheel_right_link" value="wheel_right_link"/>
    <xacro:property name="wheel_left_joint" value="wheel_left_joint"/>
    <xacro:property name="wheel_right_joint" value="wheel_right_joint"/>
    <xacro:property name="caster_wheel_front_link" value="caster_wheel_front_link"/>
    <xacro:property name="caster_wheel_back_link" value="caster_wheel_back_link"/>
    <xacro:property name="caster_base_front_link" value="caster_base_front_link"/>
    <xacro:property name="caster_base_back_link" value="caster_base_back_link"/>
    <xacro:property name="laser_front_link" value="laser_front_link"/>
    <xacro:property name="laser_back_link" value="laser_back_link"/>

    <!--**************************************************************-->
    <!--DUMMY LINK (without inertia)-->
    <!--**************************************************************-->
    <link name="${base_footprint}"/>
    

    <!--**************************************************************-->
    <!--CHASSIS (base link)-->
    <!--**************************************************************-->
    <link name="${base_link}">
    <!--INERTIA-->
    <xacro:box_inertia m="${base_mass}" w="${base_width}" h="${base_height}" d="${base_len}">
        <origin xyz="0 0 0" rpy="0 0 ${0.5 * pi - 0.5*deg_to_rad}" />
    </xacro:box_inertia>
    <!--COLLISION-->
    <collision>
        <geometry>
            <mesh filename="${chassis_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
        </geometry>
    </collision>
    <!--VISUAL-->
    <visual>
        <geometry>
            <mesh filename="${chassis_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
        </geometry>
        <xacro:insert_block name="material_aluminum"/>
    </visual>
    </link>
    <!--JOINT-->
    <joint name="base_joint" type="fixed">
        <origin xyz="0.0 0.0 ${center_mass_z + gap_from_floor}" rpy="0 0 0"/> 
        <parent link="${base_footprint}"/>
        <child link="${base_link}" />
    </joint>

    <!--**************************************************************-->
    <!--LEFT WHEEL-->
    <!--**************************************************************-->
    <link name="${wheel_left_link}">
        <!--INERTIA-->
        <!-- <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}"/> -->
        <xacro:cylinder_inertial mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_height}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <!--COLLISION-->
        <collision>
            <geometry>
                <mesh filename="${wheel_left_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
        </collision>
        <!--VISUAL-->
        <visual>
            <geometry>
                <mesh filename="${wheel_left_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
            <xacro:insert_block name="material_yellow"/>
        </visual>
    </link>
    <!--JOINT-->
    <joint name='wheel_left_joint' type='continuous'>
        <origin xyz="${wheel_left_x} ${wheel_left_y} ${wheel_left_z}" rpy="0 0 0"/>
        <child  link="${wheel_left_link}"/>
        <parent link="${base_link}"/>
        <axis rpy="0 0 0" xyz="0 1 0"/>
    </joint>

    <!--**************************************************************-->
    <!--RIGHT WHEEL-->
    <!--**************************************************************-->
    <link name="${wheel_right_link}">
        <!--INERTIA-->
        <!-- <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}"/> -->
        <xacro:cylinder_inertial mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_height}">
            <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
        </xacro:cylinder_inertial>
        <!--COLLISION-->
        <collision>
            <geometry>
            <mesh filename="${wheel_right_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
        </collision>
        <!--VISUAL-->
        <visual>
            <geometry>
            <mesh filename="${wheel_right_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
            <xacro:insert_block name="material_yellow"/>
        </visual>
    </link>
    <!--JOINT-->
    <joint name='wheel_right_joint' type='continuous'>
        <origin xyz="${wheel_right_x} ${wheel_right_y} ${wheel_right_z}" rpy="0 0 0"/>
        <child  link="${wheel_right_link}"/>
        <parent link="${base_link}"/>
        <axis rpy="0 0 0" xyz="0 1 0"/>
    </joint>

    <!--**************************************************************-->
    <!--FRONT LASER-->
    <!--**************************************************************-->
    <!-- JOINT -->
    <joint name="front_laser_joint" type="fixed">
        <origin xyz="${laser_front_x} ${laser_front_y} ${laser_front_z}" rpy="0 0 ${laser_rotation}" />
        <parent link="base_link"/>
        <child link="${laser_front_link}" />
        <dynamics damping="0.01" friction="0.0"/>
    </joint>
    <!-- LINK -->
    <link name="${laser_front_link}">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.3097539019" />
            <inertia
            ixx="0.0005844517978"
            ixy="0"
            ixz="0"
            iyy="0.00052872551237"
            iyz="0"
            izz="0.00017923555074" />
        </inertial>
        <visual>
            <!-- VISUAL -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${laser_front_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
            <xacro:insert_block name="material_yellow"/>
        </visual>
        <collision>
            <!-- COLLISION -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${laser_front_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
        </collision>
    </link>

    <!--**************************************************************-->
    <!--BACK LASER-->
    <!--**************************************************************-->
    <!-- JOINT -->
    <joint name="back_laser_joint" type="fixed">
        <origin xyz="${laser_back_x} ${laser_back_y} ${laser_back_z}" rpy="0 0 ${laser_rotation+pi}" />
        <parent link="base_link"/>
        <child link="${laser_back_link}" />
        <dynamics damping="0.01" friction="0.0"/>
    </joint>
    <!-- LINK -->
    <link name="${laser_back_link}">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.3097539019" />
            <inertia
            ixx="0.0005844517978"
            ixy="0"
            ixz="0"
            iyy="0.00052872551237"
            iyz="0"
            izz="0.00017923555074" />
        </inertial>
        <visual>
            <!-- VISUAL -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${laser_back_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
            <xacro:insert_block name="material_yellow"/>
        </visual>
        <collision>
            <!-- COLLISION -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${laser_back_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
        </collision>
    </link>

    <!--**************************************************************-->
    <!--CASTER WHEEL-->
    <!--**************************************************************-->

    <xacro:caster_wheel locationprefix="front" wheel_base_dx="${caster_base_front_x}" wheel_base_dz="${caster_base_front_z}"/>
    <xacro:caster_wheel locationprefix="back"  wheel_base_dx="${caster_base_back_x}"  wheel_base_dz="${caster_base_back_z}"/>
    
    
    <!--**************************************************************-->
    <!--BACK CASTER SPHERE WHEEL-->
    <!--**************************************************************-->
    
    <!-- <joint name="back_caster_sphere_joint" type="fixed">
        <origin xyz="${caster_base_back_x} ${caster_base_back_y} ${caster_base_back_z+caster_wheel_to_base_z}" rpy="0 0 0" />
        <parent link="${base_link}" />
        <child link="back_caster_sphere_link" />
    </joint>

    <link name="back_caster_sphere_link">
        <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_radius}">
            <origin xyx="0 0 0" rpy="0 0 0" />
        </xacro:sphere_inertia>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${caster_sphere_wheel_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
            <xacro:insert_block name="material_blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />          
            <geometry>
                <mesh filename="${caster_sphere_wheel_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
        </collision>
    </link> -->

    <!--**************************************************************-->
    <!--FRONT CASTER SPHERE WHEEL-->
    <!--**************************************************************-->

    <!-- <joint name="front_caster_sphere_joint" type="fixed">
        <origin xyz="${caster_base_front_x} ${caster_base_front_y} ${caster_base_front_z+caster_wheel_to_base_z}" rpy="0 0 0" />
        <parent link="${base_link}" />
        <child link="front_caster_sphere_link" />
    </joint>

    <link name="front_caster_sphere_link">
        <xacro:sphere_inertia m="${caster_wheel_mass}" r="${caster_radius}">
            <origin xyx="0 0 0" rpy="0 0 0" />
        </xacro:sphere_inertia>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${caster_sphere_wheel_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
            <xacro:insert_block name="material_blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />          
            <geometry>
                <mesh filename="${caster_sphere_wheel_mesh}" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}"/>
            </geometry>
        </collision>
    </link> -->

    <!--**************************************************************-->
    <!--USB CAMERA-->
    <!--**************************************************************-->
    <link name="camera_link">
      <!--INERTIA-->
      <!--Not calling macro, just small values-->
      <inertial>
        <mass value="0.005"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
      <collision>
        <geometry>
          <box size="0.1 0.05 0.05"/>
        </geometry>
      </collision>
      <visual>
        <geometry>
          <box size="0.1 0.05 0.05"/>
        </geometry>
        <material name="dark"/>
      </visual>
    </link>
    <joint name="camera_joint" type="fixed">
      <origin rpy="0 0 0" xyz="${camera_pos_x} ${camera_pos_y} ${camera_pos_z}"/>
      <child  link="camera_link"/>
      <parent link="base_link"/>
    </joint>


   
</robot>