### imu madgwick config file ###
/**:
    ros__parameters:
        constant_dt: 0.0
        declination: 0.0
        fixed_frame: "odom"
        gain: 0.1
        mag_bias_x: 0.0 
        mag_bias_y: 0.0
        mag_bias_z: 0.0
        orientation_stddev: 0.0
        publish_debug_topics: false
        publish_tf: true
        qos_overrides./parameter_events.publisher.depth: 1000
        qos_overrides./parameter_events.publisher.durability: "volatile"
        qos_overrides./parameter_events.publisher.history: "keep_last"
        qos_overrides./parameter_events.publisher.reliability: "reliable"
        qos_overrides./tf.publisher.depth: 100
        qos_overrides./tf.publisher.durability: "volatile"
        qos_overrides./tf.publisher.history: "keep_last"
        qos_overrides./tf.publisher.reliability: "reliable"
        remove_gravity_vector: false
        reverse_tf: false
        stateless: false
        use_mag: false
        use_sim_time: false
        world_frame: "enu"
        yaw_offset: 0.0
        zeta: 0.0