<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="andresito">

  <!-- <preserveFixedJoint>true</preserveFixedJoint> -->

  <!-- PROPERTIES -->
  <xacro:include filename="properties.xacro" />
   
  <!-- MACROS -->
  <xacro:include filename="wheel.xacro" />
  <!-- <xacro:include filename="leg.xacro" />
  <xacro:include filename="leg_support.xacro" />
  <xacro:include filename="gazebo.xacro" /> -->
 
  <!-- LINKS -->
  <link name="base_footprint" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${robot_depth} ${robot_width} ${robot_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${robot_depth} ${robot_width} ${robot_height}"/>
      </geometry>
    </collision>
  </link>
    
  <!-- <link name="center_rotation"></link> -->

  <link name="laser"> 
    <visual>
      <geometry>
        <cylinder length="${2*wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
  </link>

  <xacro:wheel side="left" position="front"/>
  <xacro:wheel side="left" position="back"/>
  <xacro:wheel side="right" position="front"/>
  <xacro:wheel side="right" position="back"/>
  
  <!-- JOINTS -->
  <joint name="base_joint" type="fixed">
    <origin xyz="0 -${robot_depth/2} ${wheels_height}"/>
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <joint name="base_link_left_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="${robot_width/2} ${robot_depth/2} ${wheels_height}"/>  
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_link_left_back_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_back_wheel"/>
    <origin xyz="${robot_width/2} -${robot_depth/2} ${wheels_height}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_link_right_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="-${robot_width/2} ${robot_depth/2} ${wheels_height}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_link_right_back_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin xyz="-${robot_width/2} -${robot_depth/2} ${wheels_height}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_link_laser" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0 0 ${robot_height}"/>  
    <axis xyz="0 0 1"/>
  </joint>

</robot>