
# ===========================
#  Namespace (/** es todo)
# ===========================
/**:
  ros__parameters:
    # ----- AGL_joystick PARAMS -----
    start:
      - cmd_vel
      - status

    autorun: False
    
    commands:
      #ubuntu 18.04 GAMEPAD BLUETOOTH
      ##################################
      #        axes[0] = LEFT ROUND PAD (1.0) - RIGHT ROUND PAD (-1.0) 
      #        axes[1] = UP ROUND PAD (1.0) - DOWN ROUND PAD (-1.0) 
      #        axes[2] = NOT USED
      #        axes[3] = NOT USED
      #        axes[4] = R2 PRESSED (-1.0) - R2 NOT PRESSED (1.0)
      #        axes[5] = L2 PRESSED (-1.0) - L2 NOT PRESSED (1.0)
      #        axes[6] = LEFT ARROW (1.0) - RIGHT ARROW (-1.0)
      #        axes[7] = UP ARROW (1.0) - DOWN ARROW (-1.0) 
      #        buttons[0] = A (1.0)
      #        buttons[1] = B (1.0)
      #        buttons[2] = NOT USED
      #        buttons[3] = X (1.0)
      #        buttons[4] = Y (1.0)
      #        buttons[5] = NOT USED
      #        buttons[6] = L1 (1.0)
      #        buttons[7] = R1 (1.0)
      #        buttons[8] = NOT USED
      #        buttons[9] = NOT USED
      #        buttons[10] = NOT USED
      #        buttons[11] = START (1.0)
      #        buttons[12] = NOT USED
      #        buttons[13] = LEFT PAD PRESSED (1.0)
      #        buttons[14] = RIGHT PAD PRESSED (1.0)

      # This shows axes and button position
      axes_pad_left_right: 0
      axes_pad_up_down: 1
      axes_r2: 4
      axes_l2: 5
      axes_arrow_left_right: 6
      axes_arrow_up_down: 7
      
      button_a: 0
      button_b: 1
      button_x: 3
      button_y: 4
      button_l1: 6
      button_r1: 7
      button_select: 10
      button_start: 11
      button_pad_left: 13
      button_pad_right: 14

    speed:
      linear_gain: 10.0
      angular_gain: 5.0
      velocity: 1.0