/**:
  ros__parameters:
    timeout: 10    # Timeout to detect if a node is down. 
                   # The number represents the number of cycles withour reciving status message.
                   # As the frequency of publishing the status is fixed, the final timeout in seconds 
                   # is the frequency^-1 * this value. 
                   # If frequency 10Hz and timeout 10 -> Timeout = 1 second
    
    nodes_list:    # List of the nodes name to check the status of the node.
      - LaserScan
      - Wheelmotor
    autorun: true