# ===================
#     START
# ===================
Start:
  # ----- NODOS A EJECTUAR, Solo estos se arrancaran mediante start_launch.py -----
  # Tener en cuenta que los nodos son del tipo --> <modelo>_<nombrePackage> (i.e me00_laser)
  # Por lo tanto en esta lista deberia aparecer unicamente lo siguiente:
  # 
  # - nombrePackage
  
  black_list: 
    - Description   # NO Status
    - Diagnostics   # NO Status
    - Joy           # NO Status
    - Lidar         # NO Status
    # TODO: esto queda feo ponerlo aqui si tiene Status...

  nodes_list:
    - Wheelmotor 
    - Joystick
    - Description
    - Diagnostics
    - Control
