
# ===================
#     START
# ===================
Start:
  # ----- NODOS A EJECTUAR, Solo estos se arrancaran mediante start_launch.py -----
  # Tener en cuenta que los nodos son del tipo --> <modelo>_<nombrePackage> (i.e me00_laser)
  # Por lo tanto en esta lista deberia aparecer unicamente lo siguiente:

  packages_list:
    # - agl_lidar:       
    #   - Lidar
    - agl_description:
      - Description
    - agl_joystick:
      - Joystick
      - Joy
    - agl_odometry:
      - odometry_node
    - agl_serial_interface:
      - serial_server_node
    - agl_imu:
      - ekf_local
      - ekf_global
      - imu_node

