
# ===================
#     START
# ===================
Start:
  # ----- NODOS A EJECTUAR, Solo estos se arrancaran mediante start_launch.py -----
  # Tener en cuenta que los nodos son del tipo --> <modelo>_<nombrePackage> (i.e me00_laser)
  # Por lo tanto en esta lista deberia aparecer unicamente lo siguiente:

  packages_list:
    - agl_lidar:       
      - Lidar
    - agl_description:
      - Description
    - agl_joystick:
      - Joystick
      - Joy