std_msgs/Header header #Standard ROS2 header

bool driver_ruedas  # DO0
bool frenos_ruedas  # DO1
bool seta_virtual   # DO2
bool bypass_laser   # DO3 1 for not using lasers for security, 0 for  
bool laser_p1       # DO4 Programa para robot quieto
bool laser_p2       # DO5 Programa para robot en marxa adelante
bool laser_p3       # DO6 Programa para robot en marxa atras
bool charge_battery # DO7 1 enables charge, 0 disables it
bool reservado1     # DO8
bool reservado2     # DO9
bool reservado3     # DO10
bool reservado4     # DO11
bool reservado5     # DO12
bool reservado6     # DO13
bool reservado7     # DO14
bool reservado8     # DO15