std_msgs/Header header #Standard ROS2 header

bool reservado1     # DI0
bool relay_laser    # DI1
bool relay_seta     # DI2
bool reservado2     # DI3
bool reservado3     # DI4
bool reservado4     # DI5
bool reservado5     # DI6
bool reservado6     # DI7
bool reservado7     # DI8
bool reservado8     # DI9
bool reservado9     # DI10
bool reservado10    # DI11
bool reservado11    # DI12
bool reservado12    # DI13
bool reservado13    # DI14
bool reservado14    # DI15