# ===========================
#  Namespace (/** es todo)
# ===========================
/**:
  # ===================
  #     START
  # ===================
  Start:
    # ----- Topics a publicar mediante start_launch.py -----
    topic_list:
      - status

  # ===================
  #     NODO
  # ===================
  ros__parameters:
    # ----- ME00_wheelmotor PARAMS -----
    motor:
        usb_port: "/dev/ttyUSB0"
        max_vel: 50
        min_vel: 0

    odom:
      wheel_separation: 0.400
      wheel_radius: 0.060
      frame_id: "odom"
      child_frame_id: "base_link"
      js_topic: "joint_states"
      publish_tf: false   # False en simulacion
      publish_js: false   # False en simulacion
      publish_odom: false # False en simulacion