### d455 config file ###
/**:
  ros__parameters:
    device_type: 'd455'
    serial_no: ''
    usb_port_id: ''

    initial_reset: true

    rgb_camera.profile: 640x480x15
    color_qos: "SENSOR_DATA"

    depth_module.profile: 640x480x15
    depth_qos: "SENSOR_DATA"

    infra1_qos: "SENSOR_DATA"
    infra2_qos: "SENSOR_DATA"

    gyro_fps: 200

    enable_accel: true
    enable_color: true
    enable_depth: true
    enable_gyro: true
    enable_infra1: false
    enable_infra2: false
    enable_sync: true

    enable_pointcloud: true
    filters: 'pointcloud'
    pointcloud.enable: true
    pointcloud.ordered_pc: true
    align_depth.enable: true

    pointcloud_texture_index: 0
    pointcloud_texture_stream: RS2_STREAM_COLOR

    stereo_module:
      emitter_enabled: 1
    unite_imu_method: 2 # meaning: [0 -> None, 1 -> Copy, 2 -> Linear_ interpolation]

    rosbag_filename: ''